providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium", "fontconfig"]

[phases.install]
cmds = [
  "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
  "npm ci --omit=dev --no-audit --no-fund --loglevel=error",
  "mkdir -p /usr/share/fonts/truetype/custom",
  "cp assets/fonts/*.ttf /usr/share/fonts/truetype/custom/",
  "ls -lh /usr/share/fonts/truetype/custom/ || echo 'Font directory check failed'",
  "fc-cache -fv",
  "fc-list | grep -i 'yuji\\|shippori\\|huninn\\|rampart\\|cherry' || echo 'Custom fonts not in cache'",
]

[start]
cmd = "node server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
NODE_ENV = "production"
# Note: Do NOT set PORT here - Railway sets it automatically
